//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://antt.gov.br/monitriip/v1.0/", ClrNamespace = "antt.gov.br.monitriip.v1._0")]

namespace antt.gov.br.monitriip.v1._0
{
    //using System.Runtime.Serialization;
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://antt.gov.br/monitriip/v1.0/", IsNullable = false)]
    public partial class cancelarPassagem
    {

        private string idLogField;

        private string numeroBilheteEmbarqueField;

        private string identificacaoLinhaField;

        private string dataViagemField;

        private string horaViagemField;

        private string codigoMotivoCancelamentoField;

        private string dataHoraCancelamentoField;

        private string numeroNovoBilheteEmbarqueField;

        /// <remarks/>
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        /// <remarks/>
        public string numeroBilheteEmbarque
        {
            get
            {
                return this.numeroBilheteEmbarqueField;
            }
            set
            {
                this.numeroBilheteEmbarqueField = value;
            }
        }

        /// <remarks/>
        public string identificacaoLinha
        {
            get
            {
                return this.identificacaoLinhaField;
            }
            set
            {
                this.identificacaoLinhaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public string dataViagem
        {
            get
            {
                return this.dataViagemField;
            }
            set
            {
                this.dataViagemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public string horaViagem
        {
            get
            {
                return this.horaViagemField;
            }
            set
            {
                this.horaViagemField = value;
            }
        }

        /// <remarks/>
        public string codigoMotivoCancelamento
        {
            get
            {
                return this.codigoMotivoCancelamentoField;
            }
            set
            {
                this.codigoMotivoCancelamentoField = value;
            }
        }

        /// <remarks/>
        public string dataHoraCancelamento
        {
            get
            {
                return this.dataHoraCancelamentoField;
            }
            set
            {
                this.dataHoraCancelamentoField = value;
            }
        }

        /// <remarks/>
        public string numeroNovoBilheteEmbarque
        {
            get
            {
                return this.numeroNovoBilheteEmbarqueField;
            }
            set
            {
                this.numeroNovoBilheteEmbarqueField = value;
            }
        }
    }


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "vendaPassagem", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class vendaPassagem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string codigoBilheteEmbarqueField;

        private string cnpjEmpresaField;

        private string numeroSerieEquipamentoFiscalField;

        private string numeroBilheteEmbarqueField;

        private string dataEmissaoBilheteField;

        private string horaEmissaoBilheteField;

        private string codigoCategoriaTransporteField;

        private string identificacaoLinhaField;

        private string idPontoOrigemViagemField;

        private string idPontoDestinoViagemField;

        private string codigoTipoServicoField;

        private string dataViagemField;

        private string horaViagemField;

        private string codigoTipoViagemField;

        private string numeroPoltronaField;

        private string plataformaEmbarqueField;

        private string codigoMotivoDescontoField;

        private string valorTarifaField;

        private string percentualDescontoField;

        private string aliquotaICMSField;

        private string valorPedagioField;

        private string valorTaxaEmbarqueField;

        private string valorTotalField;

        private antt.gov.br.monitriip.v1._0.informacoesPassageiro informacoesPassageiroField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string codigoBilheteEmbarque
        {
            get
            {
                return this.codigoBilheteEmbarqueField;
            }
            set
            {
                this.codigoBilheteEmbarqueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string cnpjEmpresa
        {
            get
            {
                return this.cnpjEmpresaField;
            }
            set
            {
                this.cnpjEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string numeroSerieEquipamentoFiscal
        {
            get
            {
                return this.numeroSerieEquipamentoFiscalField;
            }
            set
            {
                this.numeroSerieEquipamentoFiscalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string numeroBilheteEmbarque
        {
            get
            {
                return this.numeroBilheteEmbarqueField;
            }
            set
            {
                this.numeroBilheteEmbarqueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string dataEmissaoBilhete
        {
            get
            {
                return this.dataEmissaoBilheteField;
            }
            set
            {
                this.dataEmissaoBilheteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string horaEmissaoBilhete
        {
            get
            {
                return this.horaEmissaoBilheteField;
            }
            set
            {
                this.horaEmissaoBilheteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string codigoCategoriaTransporte
        {
            get
            {
                return this.codigoCategoriaTransporteField;
            }
            set
            {
                this.codigoCategoriaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string identificacaoLinha
        {
            get
            {
                return this.identificacaoLinhaField;
            }
            set
            {
                this.identificacaoLinhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string idPontoOrigemViagem
        {
            get
            {
                return this.idPontoOrigemViagemField;
            }
            set
            {
                this.idPontoOrigemViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string idPontoDestinoViagem
        {
            get
            {
                return this.idPontoDestinoViagemField;
            }
            set
            {
                this.idPontoDestinoViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string codigoTipoServico
        {
            get
            {
                return this.codigoTipoServicoField;
            }
            set
            {
                this.codigoTipoServicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 12)]
        public string dataViagem
        {
            get
            {
                return this.dataViagemField;
            }
            set
            {
                this.dataViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 13)]
        public string horaViagem
        {
            get
            {
                return this.horaViagemField;
            }
            set
            {
                this.horaViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 14)]
        public string codigoTipoViagem
        {
            get
            {
                return this.codigoTipoViagemField;
            }
            set
            {
                this.codigoTipoViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 15)]
        public string numeroPoltrona
        {
            get
            {
                return this.numeroPoltronaField;
            }
            set
            {
                this.numeroPoltronaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 16)]
        public string plataformaEmbarque
        {
            get
            {
                return this.plataformaEmbarqueField;
            }
            set
            {
                this.plataformaEmbarqueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 17)]
        public string codigoMotivoDesconto
        {
            get
            {
                return this.codigoMotivoDescontoField;
            }
            set
            {
                this.codigoMotivoDescontoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 18)]
        public string valorTarifa
        {
            get
            {
                return this.valorTarifaField;
            }
            set
            {
                this.valorTarifaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 19)]
        public string percentualDesconto
        {
            get
            {
                return this.percentualDescontoField;
            }
            set
            {
                this.percentualDescontoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 20)]
        public string aliquotaICMS
        {
            get
            {
                return this.aliquotaICMSField;
            }
            set
            {
                this.aliquotaICMSField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 21)]
        public string valorPedagio
        {
            get
            {
                return this.valorPedagioField;
            }
            set
            {
                this.valorPedagioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 22)]
        public string valorTaxaEmbarque
        {
            get
            {
                return this.valorTaxaEmbarqueField;
            }
            set
            {
                this.valorTaxaEmbarqueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 23)]
        public string valorTotal
        {
            get
            {
                return this.valorTotalField;
            }
            set
            {
                this.valorTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 24)]
        public antt.gov.br.monitriip.v1._0.informacoesPassageiro informacoesPassageiro
        {
            get
            {
                return this.informacoesPassageiroField;
            }
            set
            {
                this.informacoesPassageiroField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "informacoesPassageiro", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class informacoesPassageiro : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string nomePassageiroField;

        private string documentoIdentificacaoPassageiroField;

        private string cpfPassageiroField;

        private string celularPassageiroField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string nomePassageiro
        {
            get
            {
                return this.nomePassageiroField;
            }
            set
            {
                this.nomePassageiroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string documentoIdentificacaoPassageiro
        {
            get
            {
                return this.documentoIdentificacaoPassageiroField;
            }
            set
            {
                this.documentoIdentificacaoPassageiroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string cpfPassageiro
        {
            get
            {
                return this.cpfPassageiroField;
            }
            set
            {
                this.cpfPassageiroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string celularPassageiro
        {
            get
            {
                return this.celularPassageiroField;
            }
            set
            {
                this.celularPassageiroField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "resultadoOperacao", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class resultadoOperacao : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private antt.gov.br.monitriip.v1._0.codigoRetorno codigoField;

        private string mensagemField;

        private System.Nullable<System.Guid> idTransacaoField;

        private antt.gov.br.monitriip.v1._0.erro[] errosField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public antt.gov.br.monitriip.v1._0.codigoRetorno codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public System.Nullable<System.Guid> idTransacao
        {
            get
            {
                return this.idTransacaoField;
            }
            set
            {
                this.idTransacaoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public antt.gov.br.monitriip.v1._0.erro[] erros
        {
            get
            {
                return this.errosField;
            }
            set
            {
                this.errosField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "codigoRetorno", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public enum codigoRetorno : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "0")]
        _0 = 0,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "1")]
        _1 = 1,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "2")]
        _2 = 2,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "3")]
        _3 = 3,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "erro", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class erro : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private antt.gov.br.monitriip.v1._0.codigoErro codigoField;

        private string descricaoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public antt.gov.br.monitriip.v1._0.codigoErro codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "codigoErro", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public enum codigoErro : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "001")]
        _001 = 1,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "002")]
        _002 = 2,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "003")]
        _003 = 3,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "004")]
        _004 = 4,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "101")]
        _101 = 101,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "201")]
        _201 = 201,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "202")]
        _202 = 202,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "203")]
        _203 = 203,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "204")]
        _204 = 204,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "205")]
        _205 = 205,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "206")]
        _206 = 206,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "207")]
        _207 = 207,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "208")]
        _208 = 208,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "209")]
        _209 = 209,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "210")]
        _210 = 210,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "211")]
        _211 = 211,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "212")]
        _212 = 212,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "213")]
        _213 = 213,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "214")]
        _214 = 214,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "215")]
        _215 = 215,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "216")]
        _216 = 216,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "301")]
        _301 = 301,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "cartaoEmitidoRecargaEfetuada", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class cartaoEmitidoRecargaEfetuada : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaField;

        private string codigoCategoriaTransporteField;

        private string numeroCartaoField;

        private string codigoTipoCartaoField;

        private string dataVendaField;

        private string horaVendaField;

        private string bonusRecargaField;

        private string valorTotalRecargaField;

        private string saldoTotalCartaoField;

        private antt.gov.br.monitriip.v1._0.informacoesPassageiro informacoesPassageiroField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresa
        {
            get
            {
                return this.cnpjEmpresaField;
            }
            set
            {
                this.cnpjEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string codigoCategoriaTransporte
        {
            get
            {
                return this.codigoCategoriaTransporteField;
            }
            set
            {
                this.codigoCategoriaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string numeroCartao
        {
            get
            {
                return this.numeroCartaoField;
            }
            set
            {
                this.numeroCartaoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string codigoTipoCartao
        {
            get
            {
                return this.codigoTipoCartaoField;
            }
            set
            {
                this.codigoTipoCartaoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string dataVenda
        {
            get
            {
                return this.dataVendaField;
            }
            set
            {
                this.dataVendaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string horaVenda
        {
            get
            {
                return this.horaVendaField;
            }
            set
            {
                this.horaVendaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string bonusRecarga
        {
            get
            {
                return this.bonusRecargaField;
            }
            set
            {
                this.bonusRecargaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string valorTotalRecarga
        {
            get
            {
                return this.valorTotalRecargaField;
            }
            set
            {
                this.valorTotalRecargaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string saldoTotalCartao
        {
            get
            {
                return this.saldoTotalCartaoField;
            }
            set
            {
                this.saldoTotalCartaoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public antt.gov.br.monitriip.v1._0.informacoesPassageiro informacoesPassageiro
        {
            get
            {
                return this.informacoesPassageiroField;
            }
            set
            {
                this.informacoesPassageiroField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "registroOcorrenciaRodoviario", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class registroOcorrenciaRodoviario : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string numeroBilheteEmbarqueField;

        private antt.gov.br.monitriip.v1._0.informacoesReclamante informacoesReclamanteField;

        private string codigoTipoOcorrenciaField;

        private string dataOcorrenciaField;

        private string horaOcorrenciaField;

        private string dataRegistroOcorrenciaField;

        private string horaRegistroOcorrenciaField;

        private string descricaoOcorrenciaField;

        private string numeroProtocoloField;

        private string cnpjEmpresaTransporteField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string numeroBilheteEmbarque
        {
            get
            {
                return this.numeroBilheteEmbarqueField;
            }
            set
            {
                this.numeroBilheteEmbarqueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public antt.gov.br.monitriip.v1._0.informacoesReclamante informacoesReclamante
        {
            get
            {
                return this.informacoesReclamanteField;
            }
            set
            {
                this.informacoesReclamanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string codigoTipoOcorrencia
        {
            get
            {
                return this.codigoTipoOcorrenciaField;
            }
            set
            {
                this.codigoTipoOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string dataOcorrencia
        {
            get
            {
                return this.dataOcorrenciaField;
            }
            set
            {
                this.dataOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string horaOcorrencia
        {
            get
            {
                return this.horaOcorrenciaField;
            }
            set
            {
                this.horaOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string dataRegistroOcorrencia
        {
            get
            {
                return this.dataRegistroOcorrenciaField;
            }
            set
            {
                this.dataRegistroOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string horaRegistroOcorrencia
        {
            get
            {
                return this.horaRegistroOcorrenciaField;
            }
            set
            {
                this.horaRegistroOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string descricaoOcorrencia
        {
            get
            {
                return this.descricaoOcorrenciaField;
            }
            set
            {
                this.descricaoOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string numeroProtocolo
        {
            get
            {
                return this.numeroProtocoloField;
            }
            set
            {
                this.numeroProtocoloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "informacoesReclamante", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class informacoesReclamante : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string nomeReclamanteField;

        private string documentoIdentificacaoReclamanteField;

        private string enderecoReclamanteField;

        private string telefoneContatoReclamanteField;

        private string emailReclamanteField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string nomeReclamante
        {
            get
            {
                return this.nomeReclamanteField;
            }
            set
            {
                this.nomeReclamanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string documentoIdentificacaoReclamante
        {
            get
            {
                return this.documentoIdentificacaoReclamanteField;
            }
            set
            {
                this.documentoIdentificacaoReclamanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string enderecoReclamante
        {
            get
            {
                return this.enderecoReclamanteField;
            }
            set
            {
                this.enderecoReclamanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string telefoneContatoReclamante
        {
            get
            {
                return this.telefoneContatoReclamanteField;
            }
            set
            {
                this.telefoneContatoReclamanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string emailReclamante
        {
            get
            {
                return this.emailReclamanteField;
            }
            set
            {
                this.emailReclamanteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "registroOcorrenciaSemiurbano", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class registroOcorrenciaSemiurbano : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string identificacaoLinhaField;

        private string empresaResponsavelField;

        private antt.gov.br.monitriip.v1._0.informacoesReclamante informacoesReclamanteField;

        private string codigoTipoOcorrenciaField;

        private string dataOcorrenciaField;

        private string horaOcorrenciaField;

        private string dataRegistroOcorrenciaField;

        private string horaRegistroOcorrenciaField;

        private string descricaoOcorrenciaField;

        private string numeroProtocoloField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string identificacaoLinha
        {
            get
            {
                return this.identificacaoLinhaField;
            }
            set
            {
                this.identificacaoLinhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string empresaResponsavel
        {
            get
            {
                return this.empresaResponsavelField;
            }
            set
            {
                this.empresaResponsavelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public antt.gov.br.monitriip.v1._0.informacoesReclamante informacoesReclamante
        {
            get
            {
                return this.informacoesReclamanteField;
            }
            set
            {
                this.informacoesReclamanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string codigoTipoOcorrencia
        {
            get
            {
                return this.codigoTipoOcorrenciaField;
            }
            set
            {
                this.codigoTipoOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string dataOcorrencia
        {
            get
            {
                return this.dataOcorrenciaField;
            }
            set
            {
                this.dataOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string horaOcorrencia
        {
            get
            {
                return this.horaOcorrenciaField;
            }
            set
            {
                this.horaOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string dataRegistroOcorrencia
        {
            get
            {
                return this.dataRegistroOcorrenciaField;
            }
            set
            {
                this.dataRegistroOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string horaRegistroOcorrencia
        {
            get
            {
                return this.horaRegistroOcorrenciaField;
            }
            set
            {
                this.horaRegistroOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string descricaoOcorrencia
        {
            get
            {
                return this.descricaoOcorrenciaField;
            }
            set
            {
                this.descricaoOcorrenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string numeroProtocolo
        {
            get
            {
                return this.numeroProtocoloField;
            }
            set
            {
                this.numeroProtocoloField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "velocidadeTempoLocalizacao", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class velocidadeTempoLocalizacao : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string velocidadeAtualField;

        private string distanciaPercorridaField;

        private string situacaoIgnicaoMotorField;

        private string situacaoPortaVeiculoField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraEventoField;

        private string imeiField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string velocidadeAtual
        {
            get
            {
                return this.velocidadeAtualField;
            }
            set
            {
                this.velocidadeAtualField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string distanciaPercorrida
        {
            get
            {
                return this.distanciaPercorridaField;
            }
            set
            {
                this.distanciaPercorridaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string situacaoIgnicaoMotor
        {
            get
            {
                return this.situacaoIgnicaoMotorField;
            }
            set
            {
                this.situacaoIgnicaoMotorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string situacaoPortaVeiculo
        {
            get
            {
                return this.situacaoPortaVeiculoField;
            }
            set
            {
                this.situacaoPortaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string dataHoraEvento
        {
            get
            {
                return this.dataHoraEventoField;
            }
            set
            {
                this.dataHoraEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "jornadaTrabalhoMotorista", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class jornadaTrabalhoMotorista : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string cpfMotoristaField;

        private string tipoRegistroEventoField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraEventoField;

        private string imeiField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string cpfMotorista
        {
            get
            {
                return this.cpfMotoristaField;
            }
            set
            {
                this.cpfMotoristaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string tipoRegistroEvento
        {
            get
            {
                return this.tipoRegistroEventoField;
            }
            set
            {
                this.tipoRegistroEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string dataHoraEvento
        {
            get
            {
                return this.dataHoraEventoField;
            }
            set
            {
                this.dataHoraEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "detectorParada", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class detectorParada : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string codigoMotivoParadaField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraEventoField;

        private string imeiField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string codigoMotivoParada
        {
            get
            {
                return this.codigoMotivoParadaField;
            }
            set
            {
                this.codigoMotivoParadaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string dataHoraEvento
        {
            get
            {
                return this.dataHoraEventoField;
            }
            set
            {
                this.dataHoraEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "inicioFimViagemRegular", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class inicioFimViagemRegular : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string identificacaoLinhaField;

        private string codigoTipoViagemField;

        private string dataProgramadaViagemField;

        private string horaProgramadaViagemField;

        private string tipoRegistroViagemField;

        private string codigoSentidoLinhaField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraEventoField;

        private string imeiField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string identificacaoLinha
        {
            get
            {
                return this.identificacaoLinhaField;
            }
            set
            {
                this.identificacaoLinhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string codigoTipoViagem
        {
            get
            {
                return this.codigoTipoViagemField;
            }
            set
            {
                this.codigoTipoViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string dataProgramadaViagem
        {
            get
            {
                return this.dataProgramadaViagemField;
            }
            set
            {
                this.dataProgramadaViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string horaProgramadaViagem
        {
            get
            {
                return this.horaProgramadaViagemField;
            }
            set
            {
                this.horaProgramadaViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string tipoRegistroViagem
        {
            get
            {
                return this.tipoRegistroViagemField;
            }
            set
            {
                this.tipoRegistroViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string codigoSentidoLinha
        {
            get
            {
                return this.codigoSentidoLinhaField;
            }
            set
            {
                this.codigoSentidoLinhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 12)]
        public string dataHoraEvento
        {
            get
            {
                return this.dataHoraEventoField;
            }
            set
            {
                this.dataHoraEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 13)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "inicioFimViagemFretado", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class inicioFimViagemFretado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string autorizacaoViagemField;

        private string tipoRegistroViagemField;

        private string sentidoLinhaField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraEventoField;

        private string imeiField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string autorizacaoViagem
        {
            get
            {
                return this.autorizacaoViagemField;
            }
            set
            {
                this.autorizacaoViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string tipoRegistroViagem
        {
            get
            {
                return this.tipoRegistroViagemField;
            }
            set
            {
                this.tipoRegistroViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string sentidoLinha
        {
            get
            {
                return this.sentidoLinhaField;
            }
            set
            {
                this.sentidoLinhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string dataHoraEvento
        {
            get
            {
                return this.dataHoraEventoField;
            }
            set
            {
                this.dataHoraEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bilheteEmbarque", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class bilheteEmbarque : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraEventoField;

        private string imeiField;

        private antt.gov.br.monitriip.v1._0.bilhete[] bilhetesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string dataHoraEvento
        {
            get
            {
                return this.dataHoraEventoField;
            }
            set
            {
                this.dataHoraEventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public antt.gov.br.monitriip.v1._0.bilhete[] bilhetes
        {
            get
            {
                return this.bilhetesField;
            }
            set
            {
                this.bilhetesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bilhete", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class bilhete : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string numeroEquipamentoField;

        private string numeroBilheteEmbarqueField;

        private string identificacaoLinhaField;

        private string dataPrevistaViagemField;

        private string horaPrevistaViagemField;

        private string codigoDescontoField;

        private string valorTarifaField;

        private string percentualDescontoField;

        private string celularPassageiroField;

        private string idPontoOrigemViagemField;

        private string idPontoDestinoViagemField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string numeroEquipamento
        {
            get
            {
                return this.numeroEquipamentoField;
            }
            set
            {
                this.numeroEquipamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string numeroBilheteEmbarque
        {
            get
            {
                return this.numeroBilheteEmbarqueField;
            }
            set
            {
                this.numeroBilheteEmbarqueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string identificacaoLinha
        {
            get
            {
                return this.identificacaoLinhaField;
            }
            set
            {
                this.identificacaoLinhaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string dataPrevistaViagem
        {
            get
            {
                return this.dataPrevistaViagemField;
            }
            set
            {
                this.dataPrevistaViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string horaPrevistaViagem
        {
            get
            {
                return this.horaPrevistaViagemField;
            }
            set
            {
                this.horaPrevistaViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string codigoDesconto
        {
            get
            {
                return this.codigoDescontoField;
            }
            set
            {
                this.codigoDescontoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string valorTarifa
        {
            get
            {
                return this.valorTarifaField;
            }
            set
            {
                this.valorTarifaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string percentualDesconto
        {
            get
            {
                return this.percentualDescontoField;
            }
            set
            {
                this.percentualDescontoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string celularPassageiro
        {
            get
            {
                return this.celularPassageiroField;
            }
            set
            {
                this.celularPassageiroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string idPontoOrigemViagem
        {
            get
            {
                return this.idPontoOrigemViagemField;
            }
            set
            {
                this.idPontoOrigemViagemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string idPontoDestinoViagem
        {
            get
            {
                return this.idPontoDestinoViagemField;
            }
            set
            {
                this.idPontoDestinoViagemField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "leitorCartaoRFID", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class leitorCartaoRFID : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idLogField;

        private string cnpjEmpresaTransporteField;

        private string placaVeiculoField;

        private string latitudeField;

        private string longitudeField;

        private string pdopField;

        private string dataHoraAberturaPortaField;

        private string imeiField;

        private antt.gov.br.monitriip.v1._0.cartao[] cartoesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string idLog
        {
            get
            {
                return this.idLogField;
            }
            set
            {
                this.idLogField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string cnpjEmpresaTransporte
        {
            get
            {
                return this.cnpjEmpresaTransporteField;
            }
            set
            {
                this.cnpjEmpresaTransporteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string placaVeiculo
        {
            get
            {
                return this.placaVeiculoField;
            }
            set
            {
                this.placaVeiculoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string dataHoraAberturaPorta
        {
            get
            {
                return this.dataHoraAberturaPortaField;
            }
            set
            {
                this.dataHoraAberturaPortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public antt.gov.br.monitriip.v1._0.cartao[] cartoes
        {
            get
            {
                return this.cartoesField;
            }
            set
            {
                this.cartoesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "cartao", Namespace = "http://antt.gov.br/monitriip/v1.0/")]
    public partial class cartao : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string numeroCartaoField;

        private string codigoTipoCartaoField;

        private string valorTarifaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string numeroCartao
        {
            get
            {
                return this.numeroCartaoField;
            }
            set
            {
                this.numeroCartaoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string codigoTipoCartao
        {
            get
            {
                return this.codigoTipoCartaoField;
            }
            set
            {
                this.codigoTipoCartaoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string valorTarifa
        {
            get
            {
                return this.valorTarifaField;
            }
            set
            {
                this.valorTarifaField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://antt.gov.br/monitriip/v1.0/", ConfigurationName = "IMonitriipService")]
public interface IMonitriipService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVendaPassagem", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVendaPassagemRespon" +
        "se")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogVendaPassagem(antt.gov.br.monitriip.v1._0.vendaPassagem dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVendaPassagem", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVendaPassagemRespon" +
        "se")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogVendaPassagemAsync(antt.gov.br.monitriip.v1._0.vendaPassagem dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogCartaoEmitidoRecarg" +
        "aEfetuada", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogCartaoEmitidoRecarg" +
        "aEfetuadaResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogCartaoEmitidoRecargaEfetuada(antt.gov.br.monitriip.v1._0.cartaoEmitidoRecargaEfetuada dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogCartaoEmitidoRecarg" +
        "aEfetuada", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogCartaoEmitidoRecarg" +
        "aEfetuadaResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogCartaoEmitidoRecargaEfetuadaAsync(antt.gov.br.monitriip.v1._0.cartaoEmitidoRecargaEfetuada dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaR" +
        "odoviario", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaR" +
        "odoviarioResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogRegistroOcorrenciaRodoviario(antt.gov.br.monitriip.v1._0.registroOcorrenciaRodoviario dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaR" +
        "odoviario", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaR" +
        "odoviarioResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogRegistroOcorrenciaRodoviarioAsync(antt.gov.br.monitriip.v1._0.registroOcorrenciaRodoviario dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaS" +
        "emiurbano", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaS" +
        "emiurbanoResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogRegistroOcorrenciaSemiurbano(antt.gov.br.monitriip.v1._0.registroOcorrenciaSemiurbano dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaS" +
        "emiurbano", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogRegistroOcorrenciaS" +
        "emiurbanoResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogRegistroOcorrenciaSemiurbanoAsync(antt.gov.br.monitriip.v1._0.registroOcorrenciaSemiurbano dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVelocidadeTempoLoca" +
        "lizacao", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVelocidadeTempoLoca" +
        "lizacaoResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogVelocidadeTempoLocalizacao(antt.gov.br.monitriip.v1._0.velocidadeTempoLocalizacao dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVelocidadeTempoLoca" +
        "lizacao", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogVelocidadeTempoLoca" +
        "lizacaoResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogVelocidadeTempoLocalizacaoAsync(antt.gov.br.monitriip.v1._0.velocidadeTempoLocalizacao dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogJornadaTrabalhoMoto" +
        "rista", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogJornadaTrabalhoMoto" +
        "ristaResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogJornadaTrabalhoMotorista(antt.gov.br.monitriip.v1._0.jornadaTrabalhoMotorista dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogJornadaTrabalhoMoto" +
        "rista", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogJornadaTrabalhoMoto" +
        "ristaResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogJornadaTrabalhoMotoristaAsync(antt.gov.br.monitriip.v1._0.jornadaTrabalhoMotorista dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogDetectorParada", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogDetectorParadaRespo" +
        "nse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogDetectorParada(antt.gov.br.monitriip.v1._0.detectorParada dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogDetectorParada", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogDetectorParadaRespo" +
        "nse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogDetectorParadaAsync(antt.gov.br.monitriip.v1._0.detectorParada dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemRegu" +
        "lar", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemRegu" +
        "larResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogInicioFimViagemRegular(antt.gov.br.monitriip.v1._0.inicioFimViagemRegular dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemRegu" +
        "lar", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemRegu" +
        "larResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogInicioFimViagemRegularAsync(antt.gov.br.monitriip.v1._0.inicioFimViagemRegular dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemFret" +
        "ado", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemFret" +
        "adoResponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogInicioFimViagemFretado(antt.gov.br.monitriip.v1._0.inicioFimViagemFretado dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemFret" +
        "ado", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogInicioFimViagemFret" +
        "adoResponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogInicioFimViagemFretadoAsync(antt.gov.br.monitriip.v1._0.inicioFimViagemFretado dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogBilheteEmbarque", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogBilheteEmbarqueResp" +
        "onse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogBilheteEmbarque(antt.gov.br.monitriip.v1._0.bilheteEmbarque dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogBilheteEmbarque", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogBilheteEmbarqueResp" +
        "onse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogBilheteEmbarqueAsync(antt.gov.br.monitriip.v1._0.bilheteEmbarque dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogLeitorCartaoRFID", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogLeitorCartaoRFIDRes" +
        "ponse")]
    antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogLeitorCartaoRFID(antt.gov.br.monitriip.v1._0.leitorCartaoRFID dto);

    [System.ServiceModel.OperationContractAttribute(Action = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogLeitorCartaoRFID", ReplyAction = "http://antt.gov.br/monitriip/v1.0/IMonitriipService/InserirLogLeitorCartaoRFIDRes" +
        "ponse")]
    System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogLeitorCartaoRFIDAsync(antt.gov.br.monitriip.v1._0.leitorCartaoRFID dto);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMonitriipServiceChannel : IMonitriipService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MonitriipServiceClient : System.ServiceModel.ClientBase<IMonitriipService>, IMonitriipService
{

    public MonitriipServiceClient()
    {
    }

    public MonitriipServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public MonitriipServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MonitriipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MonitriipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogVendaPassagem(antt.gov.br.monitriip.v1._0.vendaPassagem dto)
    {
        return base.Channel.InserirLogVendaPassagem(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogVendaPassagemAsync(antt.gov.br.monitriip.v1._0.vendaPassagem dto)
    {
        return base.Channel.InserirLogVendaPassagemAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogCartaoEmitidoRecargaEfetuada(antt.gov.br.monitriip.v1._0.cartaoEmitidoRecargaEfetuada dto)
    {
        return base.Channel.InserirLogCartaoEmitidoRecargaEfetuada(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogCartaoEmitidoRecargaEfetuadaAsync(antt.gov.br.monitriip.v1._0.cartaoEmitidoRecargaEfetuada dto)
    {
        return base.Channel.InserirLogCartaoEmitidoRecargaEfetuadaAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogRegistroOcorrenciaRodoviario(antt.gov.br.monitriip.v1._0.registroOcorrenciaRodoviario dto)
    {
        return base.Channel.InserirLogRegistroOcorrenciaRodoviario(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogRegistroOcorrenciaRodoviarioAsync(antt.gov.br.monitriip.v1._0.registroOcorrenciaRodoviario dto)
    {
        return base.Channel.InserirLogRegistroOcorrenciaRodoviarioAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogRegistroOcorrenciaSemiurbano(antt.gov.br.monitriip.v1._0.registroOcorrenciaSemiurbano dto)
    {
        return base.Channel.InserirLogRegistroOcorrenciaSemiurbano(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogRegistroOcorrenciaSemiurbanoAsync(antt.gov.br.monitriip.v1._0.registroOcorrenciaSemiurbano dto)
    {
        return base.Channel.InserirLogRegistroOcorrenciaSemiurbanoAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogVelocidadeTempoLocalizacao(antt.gov.br.monitriip.v1._0.velocidadeTempoLocalizacao dto)
    {
        return base.Channel.InserirLogVelocidadeTempoLocalizacao(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogVelocidadeTempoLocalizacaoAsync(antt.gov.br.monitriip.v1._0.velocidadeTempoLocalizacao dto)
    {
        return base.Channel.InserirLogVelocidadeTempoLocalizacaoAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogJornadaTrabalhoMotorista(antt.gov.br.monitriip.v1._0.jornadaTrabalhoMotorista dto)
    {
        return base.Channel.InserirLogJornadaTrabalhoMotorista(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogJornadaTrabalhoMotoristaAsync(antt.gov.br.monitriip.v1._0.jornadaTrabalhoMotorista dto)
    {
        return base.Channel.InserirLogJornadaTrabalhoMotoristaAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogDetectorParada(antt.gov.br.monitriip.v1._0.detectorParada dto)
    {
        return base.Channel.InserirLogDetectorParada(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogDetectorParadaAsync(antt.gov.br.monitriip.v1._0.detectorParada dto)
    {
        return base.Channel.InserirLogDetectorParadaAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogInicioFimViagemRegular(antt.gov.br.monitriip.v1._0.inicioFimViagemRegular dto)
    {
        return base.Channel.InserirLogInicioFimViagemRegular(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogInicioFimViagemRegularAsync(antt.gov.br.monitriip.v1._0.inicioFimViagemRegular dto)
    {
        return base.Channel.InserirLogInicioFimViagemRegularAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogInicioFimViagemFretado(antt.gov.br.monitriip.v1._0.inicioFimViagemFretado dto)
    {
        return base.Channel.InserirLogInicioFimViagemFretado(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogInicioFimViagemFretadoAsync(antt.gov.br.monitriip.v1._0.inicioFimViagemFretado dto)
    {
        return base.Channel.InserirLogInicioFimViagemFretadoAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogBilheteEmbarque(antt.gov.br.monitriip.v1._0.bilheteEmbarque dto)
    {
        return base.Channel.InserirLogBilheteEmbarque(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogBilheteEmbarqueAsync(antt.gov.br.monitriip.v1._0.bilheteEmbarque dto)
    {
        return base.Channel.InserirLogBilheteEmbarqueAsync(dto);
    }

    public antt.gov.br.monitriip.v1._0.resultadoOperacao InserirLogLeitorCartaoRFID(antt.gov.br.monitriip.v1._0.leitorCartaoRFID dto)
    {
        return base.Channel.InserirLogLeitorCartaoRFID(dto);
    }

    public System.Threading.Tasks.Task<antt.gov.br.monitriip.v1._0.resultadoOperacao> InserirLogLeitorCartaoRFIDAsync(antt.gov.br.monitriip.v1._0.leitorCartaoRFID dto)
    {
        return base.Channel.InserirLogLeitorCartaoRFIDAsync(dto);
    }
}
