//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class inicioFimViagemRegular {
    
    private sbyte idLogField;
    
    private string cnpjEmpresaTransporteField;
    
    private string placaVeiculoField;
    
    private string identificacaoLinhaField;
    
    private sbyte codigoTipoViagemField;
    
    private System.DateTime dataProgramadaViagemField;
    
    private System.DateTime horaProgramadaViagemField;
    
    private sbyte tipoRegistroViagemField;
    
    private sbyte codigoSentidoLinhaField;
    
    private decimal latitudeField;
    
    private decimal longitudeField;
    
    private decimal pdopField;
    
    private System.DateTime dataHoraEventoField;
    
    private long imeiField;
    
    /// <remarks/>
    public sbyte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public string cnpjEmpresaTransporte {
        get {
            return this.cnpjEmpresaTransporteField;
        }
        set {
            this.cnpjEmpresaTransporteField = value;
        }
    }
    
    /// <remarks/>
    public string placaVeiculo {
        get {
            return this.placaVeiculoField;
        }
        set {
            this.placaVeiculoField = value;
        }
    }
    
    /// <remarks/>
    public string identificacaoLinha {
        get {
            return this.identificacaoLinhaField;
        }
        set {
            this.identificacaoLinhaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoTipoViagem {
        get {
            return this.codigoTipoViagemField;
        }
        set {
            this.codigoTipoViagemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataProgramadaViagem {
        get {
            return this.dataProgramadaViagemField;
        }
        set {
            this.dataProgramadaViagemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime horaProgramadaViagem {
        get {
            return this.horaProgramadaViagemField;
        }
        set {
            this.horaProgramadaViagemField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tipoRegistroViagem {
        get {
            return this.tipoRegistroViagemField;
        }
        set {
            this.tipoRegistroViagemField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoSentidoLinha {
        get {
            return this.codigoSentidoLinhaField;
        }
        set {
            this.codigoSentidoLinhaField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal pdop {
        get {
            return this.pdopField;
        }
        set {
            this.pdopField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dataHoraEvento {
        get {
            return this.dataHoraEventoField;
        }
        set {
            this.dataHoraEventoField = value;
        }
    }
    
    /// <remarks/>
    public long imei {
        get {
            return this.imeiField;
        }
        set {
            this.imeiField = value;
        }
    }
}
