//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class jornadaTrabalhoMotorista {
    
    private sbyte idLogField;
    
    private string cnpjEmpresaTransporteField;
    
    private string placaVeiculoField;
    
    private string cpfMotoristaField;
    
    private sbyte tipoRegistroEventoField;
    
    private decimal latitudeField;
    
    private decimal longitudeField;
    
    private decimal pdopField;
    
    private System.DateTime dataHoraEventoField;
    
    private long imeiField;
    
    /// <remarks/>
    public sbyte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public string cnpjEmpresaTransporte {
        get {
            return this.cnpjEmpresaTransporteField;
        }
        set {
            this.cnpjEmpresaTransporteField = value;
        }
    }
    
    /// <remarks/>
    public string placaVeiculo {
        get {
            return this.placaVeiculoField;
        }
        set {
            this.placaVeiculoField = value;
        }
    }
    
    /// <remarks/>
    public string cpfMotorista {
        get {
            return this.cpfMotoristaField;
        }
        set {
            this.cpfMotoristaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tipoRegistroEvento {
        get {
            return this.tipoRegistroEventoField;
        }
        set {
            this.tipoRegistroEventoField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal pdop {
        get {
            return this.pdopField;
        }
        set {
            this.pdopField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dataHoraEvento {
        get {
            return this.dataHoraEventoField;
        }
        set {
            this.dataHoraEventoField = value;
        }
    }
    
    /// <remarks/>
    public long imei {
        get {
            return this.imeiField;
        }
        set {
            this.imeiField = value;
        }
    }
}
