//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class leitorCartaoRFID {
    
    private sbyte idLogField;
    
    private string cnpjEmpresaTransporteField;
    
    private string placaVeiculoField;
    
    private decimal latitudeField;
    
    private decimal longitudeField;
    
    private decimal pdopField;
    
    private System.DateTime dataHoraAberturaPortaField;
    
    private long imeiField;
    
    private leitorCartaoRFIDCartao[] cartoesField;
    
    /// <remarks/>
    public sbyte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public string cnpjEmpresaTransporte {
        get {
            return this.cnpjEmpresaTransporteField;
        }
        set {
            this.cnpjEmpresaTransporteField = value;
        }
    }
    
    /// <remarks/>
    public string placaVeiculo {
        get {
            return this.placaVeiculoField;
        }
        set {
            this.placaVeiculoField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal pdop {
        get {
            return this.pdopField;
        }
        set {
            this.pdopField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dataHoraAberturaPorta {
        get {
            return this.dataHoraAberturaPortaField;
        }
        set {
            this.dataHoraAberturaPortaField = value;
        }
    }
    
    /// <remarks/>
    public long imei {
        get {
            return this.imeiField;
        }
        set {
            this.imeiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("cartao", IsNullable=false)]
    public leitorCartaoRFIDCartao[] cartoes {
        get {
            return this.cartoesField;
        }
        set {
            this.cartoesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
public partial class leitorCartaoRFIDCartao {
    
    private string numeroCartaoField;
    
    private sbyte codigoTipoCartaoField;
    
    private decimal valorTarifaField;
    
    /// <remarks/>
    public string numeroCartao {
        get {
            return this.numeroCartaoField;
        }
        set {
            this.numeroCartaoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoTipoCartao {
        get {
            return this.codigoTipoCartaoField;
        }
        set {
            this.codigoTipoCartaoField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorTarifa {
        get {
            return this.valorTarifaField;
        }
        set {
            this.valorTarifaField = value;
        }
    }
}
