//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class vendaPassagem {
    
    private sbyte idLogField;
    
    private sbyte codigoBilheteEmbarqueField;
    
    private string cnpjEmpresaField;
    
    private string numeroSerieEquipamentoFiscalField;
    
    private string numeroBilheteEmbarqueField;
    
    private System.DateTime dataEmissaoBilheteField;
    
    private System.DateTime horaEmissaoBilheteField;
    
    private sbyte codigoCategoriaTransporteField;
    
    private string identificacaoLinhaField;
    
    private long idPontoOrigemViagemField;
    
    private long idPontoDestinoViagemField;
    
    private sbyte codigoTipoServicoField;
    
    private System.DateTime dataViagemField;
    
    private System.DateTime horaViagemField;
    
    private sbyte codigoTipoViagemField;
    
    private string numeroPoltronaField;
    
    private string plataformaEmbarqueField;
    
    private sbyte codigoMotivoDescontoField;
    
    private decimal valorTarifaField;
    
    private decimal percentualDescontoField;
    
    private decimal aliquotaICMSField;
    
    private decimal valorPedagioField;
    
    private decimal valorTaxaEmbarqueField;
    
    private decimal valorTotalField;
    
    private vendaPassagemInformacoesPassageiro informacoesPassageiroField;
    
    /// <remarks/>
    public sbyte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoBilheteEmbarque {
        get {
            return this.codigoBilheteEmbarqueField;
        }
        set {
            this.codigoBilheteEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    public string cnpjEmpresa {
        get {
            return this.cnpjEmpresaField;
        }
        set {
            this.cnpjEmpresaField = value;
        }
    }
    
    /// <remarks/>
    public string numeroSerieEquipamentoFiscal {
        get {
            return this.numeroSerieEquipamentoFiscalField;
        }
        set {
            this.numeroSerieEquipamentoFiscalField = value;
        }
    }
    
    /// <remarks/>
    public string numeroBilheteEmbarque {
        get {
            return this.numeroBilheteEmbarqueField;
        }
        set {
            this.numeroBilheteEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataEmissaoBilhete {
        get {
            return this.dataEmissaoBilheteField;
        }
        set {
            this.dataEmissaoBilheteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime horaEmissaoBilhete {
        get {
            return this.horaEmissaoBilheteField;
        }
        set {
            this.horaEmissaoBilheteField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoCategoriaTransporte {
        get {
            return this.codigoCategoriaTransporteField;
        }
        set {
            this.codigoCategoriaTransporteField = value;
        }
    }
    
    /// <remarks/>
    public string identificacaoLinha {
        get {
            return this.identificacaoLinhaField;
        }
        set {
            this.identificacaoLinhaField = value;
        }
    }
    
    /// <remarks/>
    public long idPontoOrigemViagem {
        get {
            return this.idPontoOrigemViagemField;
        }
        set {
            this.idPontoOrigemViagemField = value;
        }
    }
    
    /// <remarks/>
    public long idPontoDestinoViagem {
        get {
            return this.idPontoDestinoViagemField;
        }
        set {
            this.idPontoDestinoViagemField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoTipoServico {
        get {
            return this.codigoTipoServicoField;
        }
        set {
            this.codigoTipoServicoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataViagem {
        get {
            return this.dataViagemField;
        }
        set {
            this.dataViagemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime horaViagem {
        get {
            return this.horaViagemField;
        }
        set {
            this.horaViagemField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoTipoViagem {
        get {
            return this.codigoTipoViagemField;
        }
        set {
            this.codigoTipoViagemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numeroPoltrona {
        get {
            return this.numeroPoltronaField;
        }
        set {
            this.numeroPoltronaField = value;
        }
    }
    
    /// <remarks/>
    public string plataformaEmbarque {
        get {
            return this.plataformaEmbarqueField;
        }
        set {
            this.plataformaEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoMotivoDesconto {
        get {
            return this.codigoMotivoDescontoField;
        }
        set {
            this.codigoMotivoDescontoField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorTarifa {
        get {
            return this.valorTarifaField;
        }
        set {
            this.valorTarifaField = value;
        }
    }
    
    /// <remarks/>
    public decimal percentualDesconto {
        get {
            return this.percentualDescontoField;
        }
        set {
            this.percentualDescontoField = value;
        }
    }
    
    /// <remarks/>
    public decimal aliquotaICMS {
        get {
            return this.aliquotaICMSField;
        }
        set {
            this.aliquotaICMSField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorPedagio {
        get {
            return this.valorPedagioField;
        }
        set {
            this.valorPedagioField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorTaxaEmbarque {
        get {
            return this.valorTaxaEmbarqueField;
        }
        set {
            this.valorTaxaEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorTotal {
        get {
            return this.valorTotalField;
        }
        set {
            this.valorTotalField = value;
        }
    }
    
    /// <remarks/>
    public vendaPassagemInformacoesPassageiro informacoesPassageiro {
        get {
            return this.informacoesPassageiroField;
        }
        set {
            this.informacoesPassageiroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
public partial class vendaPassagemInformacoesPassageiro {
    
    private string nomePassageiroField;
    
    private string documentoIdentificacaoPassageiroField;
    
    private string cpfPassageiroField;
    
    private string celularPassageiroField;
    
    /// <remarks/>
    public string nomePassageiro {
        get {
            return this.nomePassageiroField;
        }
        set {
            this.nomePassageiroField = value;
        }
    }
    
    /// <remarks/>
    public string documentoIdentificacaoPassageiro {
        get {
            return this.documentoIdentificacaoPassageiroField;
        }
        set {
            this.documentoIdentificacaoPassageiroField = value;
        }
    }
    
    /// <remarks/>
    public string cpfPassageiro {
        get {
            return this.cpfPassageiroField;
        }
        set {
            this.cpfPassageiroField = value;
        }
    }
    
    /// <remarks/>
    public string celularPassageiro {
        get {
            return this.celularPassageiroField;
        }
        set {
            this.celularPassageiroField = value;
        }
    }
}
