//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class cancelarPassagem {
    
    private byte idLogField;
    
    private string numeroBilheteEmbarqueField;
    
    private string identificacaoLinhaField;
    
    private System.DateTime dataViagemField;
    
    private System.DateTime horaViagemField;
    
    private byte codigoMotivoCancelamentoField;
    
    private System.DateTime dataHoraCancelamentoField;
    
    private string numeroNovoBilheteEmbarqueField;
    
    /// <remarks/>
    public byte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public string numeroBilheteEmbarque {
        get {
            return this.numeroBilheteEmbarqueField;
        }
        set {
            this.numeroBilheteEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    public string identificacaoLinha {
        get {
            return this.identificacaoLinhaField;
        }
        set {
            this.identificacaoLinhaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataViagem {
        get {
            return this.dataViagemField;
        }
        set {
            this.dataViagemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime horaViagem {
        get {
            return this.horaViagemField;
        }
        set {
            this.horaViagemField = value;
        }
    }
    
    /// <remarks/>
    public byte codigoMotivoCancelamento {
        get {
            return this.codigoMotivoCancelamentoField;
        }
        set {
            this.codigoMotivoCancelamentoField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dataHoraCancelamento {
        get {
            return this.dataHoraCancelamentoField;
        }
        set {
            this.dataHoraCancelamentoField = value;
        }
    }
    
    /// <remarks/>
    public string numeroNovoBilheteEmbarque {
        get {
            return this.numeroNovoBilheteEmbarqueField;
        }
        set {
            this.numeroNovoBilheteEmbarqueField = value;
        }
    }
}
