//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class reembolsoCartao {
    
    private byte idLogField;
    
    private string numeroCartaoField;
    
    private byte codigoTipoCartaoField;
    
    private System.DateTime dataHoraReembolsoField;
    
    private byte codigoMotivoReembolsoField;
    
    private decimal valorReembolsoField;
    
    /// <remarks/>
    public byte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public string numeroCartao {
        get {
            return this.numeroCartaoField;
        }
        set {
            this.numeroCartaoField = value;
        }
    }
    
    /// <remarks/>
    public byte codigoTipoCartao {
        get {
            return this.codigoTipoCartaoField;
        }
        set {
            this.codigoTipoCartaoField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dataHoraReembolso {
        get {
            return this.dataHoraReembolsoField;
        }
        set {
            this.dataHoraReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public byte codigoMotivoReembolso {
        get {
            return this.codigoMotivoReembolsoField;
        }
        set {
            this.codigoMotivoReembolsoField = value;
        }
    }
    
    /// <remarks/>
    public decimal valorReembolso {
        get {
            return this.valorReembolsoField;
        }
        set {
            this.valorReembolsoField = value;
        }
    }
}
