//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://antt.gov.br/monitriip/v1.0/", IsNullable=false)]
public partial class registroOcorrenciaRodoviario {
    
    private sbyte idLogField;
    
    private string numeroBilheteEmbarqueField;
    
    private registroOcorrenciaRodoviarioInformacoesReclamante informacoesReclamanteField;
    
    private sbyte codigoTipoOcorrenciaField;
    
    private System.DateTime dataOcorrenciaField;
    
    private System.DateTime horaOcorrenciaField;
    
    private System.DateTime dataRegistroOcorrenciaField;
    
    private System.DateTime horaRegistroOcorrenciaField;
    
    private string descricaoOcorrenciaField;
    
    private string numeroProtocoloField;
    
    /// <remarks/>
    public sbyte idLog {
        get {
            return this.idLogField;
        }
        set {
            this.idLogField = value;
        }
    }
    
    /// <remarks/>
    public string numeroBilheteEmbarque {
        get {
            return this.numeroBilheteEmbarqueField;
        }
        set {
            this.numeroBilheteEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    public registroOcorrenciaRodoviarioInformacoesReclamante informacoesReclamante {
        get {
            return this.informacoesReclamanteField;
        }
        set {
            this.informacoesReclamanteField = value;
        }
    }
    
    /// <remarks/>
    public sbyte codigoTipoOcorrencia {
        get {
            return this.codigoTipoOcorrenciaField;
        }
        set {
            this.codigoTipoOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataOcorrencia {
        get {
            return this.dataOcorrenciaField;
        }
        set {
            this.dataOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime horaOcorrencia {
        get {
            return this.horaOcorrenciaField;
        }
        set {
            this.horaOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataRegistroOcorrencia {
        get {
            return this.dataRegistroOcorrenciaField;
        }
        set {
            this.dataRegistroOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime horaRegistroOcorrencia {
        get {
            return this.horaRegistroOcorrenciaField;
        }
        set {
            this.horaRegistroOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    public string descricaoOcorrencia {
        get {
            return this.descricaoOcorrenciaField;
        }
        set {
            this.descricaoOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    public string numeroProtocolo {
        get {
            return this.numeroProtocoloField;
        }
        set {
            this.numeroProtocoloField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://antt.gov.br/monitriip/v1.0/")]
public partial class registroOcorrenciaRodoviarioInformacoesReclamante {
    
    private string nomeReclamanteField;
    
    private string documentoIdentificacaoReclamanteField;
    
    private string enderecoReclamanteField;
    
    private string telefoneContatoReclamanteField;
    
    private string emailReclamanteField;
    
    /// <remarks/>
    public string nomeReclamante {
        get {
            return this.nomeReclamanteField;
        }
        set {
            this.nomeReclamanteField = value;
        }
    }
    
    /// <remarks/>
    public string documentoIdentificacaoReclamante {
        get {
            return this.documentoIdentificacaoReclamanteField;
        }
        set {
            this.documentoIdentificacaoReclamanteField = value;
        }
    }
    
    /// <remarks/>
    public string enderecoReclamante {
        get {
            return this.enderecoReclamanteField;
        }
        set {
            this.enderecoReclamanteField = value;
        }
    }
    
    /// <remarks/>
    public string telefoneContatoReclamante {
        get {
            return this.telefoneContatoReclamanteField;
        }
        set {
            this.telefoneContatoReclamanteField = value;
        }
    }
    
    /// <remarks/>
    public string emailReclamante {
        get {
            return this.emailReclamanteField;
        }
        set {
            this.emailReclamanteField = value;
        }
    }
}
